version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: conectar_postgres
    environment:
      POSTGRES_DB: conectar_db
      POSTGRES_USER: conectar_user
      POSTGRES_PASSWORD: conectar_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - conectar_network

  backend:
    build: .
    container_name: conectar_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=conectar_user
      - DATABASE_PASSWORD=conectar_password
      - DATABASE_NAME=conectar_db
      - JWT_SECRET=your_jwt_secret_here
      - APP_PORT=3000
      - CORS_ORIGIN=http://localhost:3001
    depends_on:
      - postgres
    networks:
      - conectar_network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  conectar_network:
    driver: bridge